### PR TITLE
Update vagrant-ansible.md

### PR DESCRIPTION
**Pull request by XavierVallot**
just a tiny precision :-)

### CODE REVIEW

**Review by bocharsky-bw — CHANGES_REQUESTED** [review]
Hey @XavierVallot, I agree with you but we really want to match the video, especially when we have subtitles for this course, see `CC` icon in the right bottom corner of the video player (ideally we want subtitles for all our courses). But I think we can add a note. We have a special syntax for that:

```
***TIP
If you're inside the VM, for stepping out of it simply run:

```terminal-silent
exit
\```
***
```

So if you revert your changes and add this tip below the `vagrant reload` code block - I'd be glad to merge it.

**Comment by XavierVallot** [comment]
Done :-)

**Comment by MolloKhan** [comment]
Look's good to me, merging!

**Comment by bocharsky-bw** [comment]
For me too.

Thanks, Xavier!

**Pull request merged**
